### ISSUE TITLE
Out of Range exception when attemp to encrypt text of custom length

### ISSUE THREAD

**Issue by nikamon** [Finnetrib/StegProject#1]
Branch: Master

Steps:
1. Take ecnryption text  f.e. ("Стеганография. Скрываем текстовую информацию в bmp файле. Практическая реализация на C#")
2. Take default container (source picture from habr post)
3. Try to ecrypt it

Expected result: success
Actual result: Error
![image](https://user-images.githubusercontent.com/54987615/116823671-60a40600-ab8e-11eb-833d-c6f519249e64.png)

**Comment by nikamon** [comment]
Предлагаю следующий фикс:
![image](https://user-images.githubusercontent.com/54987615/116824013-89c59600-ab90-11eb-809f-93078730f3fe.png)
![image](https://user-images.githubusercontent.com/54987615/116824016-921dd100-ab90-11eb-9af8-b2a2b3a67f01.png)

**Comment by Finnetrib** [comment]
Fixed, thanks!
[#40e7f27 ](https://github.com/Finnetrib/StegProject/commit/40e7f27525f5623378373dd7172668e1ec5c93ac)
